services:
  - type: web
    name: trading-rag-backend
    env: python
    region: oregon
    plan: starter
    runtime: python-3.11.6
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: API_BASE_URL
        value: https://litellm.deriv.ai/v1
      - key: OPENAI_MODEL_NAME
        value: gpt-4o-mini
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,http://127.0.0.1:3000,https://trading-rag-frontend.vercel.app,https://rag-trading-knowledge-management.vercel.app 